name: Build Kernel CAF Vayu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
      with:
        ref: caf

    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache cgit flex glibc-source libelf-dev libssl-dev libstdc++6 git-core gnupg gperf zip unzip curl gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu

    - name: Build Kernel
      run: |
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make O=out vayu_defconfig
        make O=out -j$(nproc)

    - name: Package
      run: |
        git clone https://github.com/osm0sis/AnyKernel3 --depth=1
        cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
        cd AnyKernel3
        zip -r9 ../kernel-vayu.zip *

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Hasil-Kernel
        path: kernel-vayu.zip
