name: Build Kernel CAF Vayu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
      with:
        ref: caf

    - name: Install Dependensi
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential flex libelf-dev libssl-dev git-core zip unzip curl gcc-aarch64-linux-gnu

    - name: Compile Kernel
      run: |
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make O=out vayu_defconfig
        make O=out -j$(nproc)

    - name: Package & Upload
      run: |
        git clone https://github.com/osm0sis/AnyKernel3 --depth=1
        # Menggunakan wildcard untuk menangkap file Image hasil build
        find out/arch/arm64/boot/ -name "Image*" -exec cp {} AnyKernel3/ \;
        cd AnyKernel3
        zip -r9 ../kernel-vayu.zip *
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Hasil-Kernel-Final
        path: kernel-vayu.zip
